name: Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.7.3'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint